/*!
 * Copyright (c) 2024 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

const Groq = require('groq-sdk');

module.exports = {
  friendlyName: 'Send card data to LLM',

  description: 'Send card information to Groq API and return structured response',

  inputs: {
    card: {
      type: 'ref',
      required: true,
      description: 'The card object to send to LLM',
    },
    list: {
      type: 'ref',
      required: true,
      description: 'The list containing the card',
    },
    board: {
      type: 'ref',
      required: true,
      description: 'The board containing the list',
    },
  },

  exits: {
    success: {
      description: 'LLM response received successfully',
    },
    apiError: {
      description: 'Error calling Groq API',
    },
    configError: {
      description: 'Groq API not configured',
    },
  },

  async fn(inputs) {
    // Check if Groq API key is configured
    const groqApiKey = process.env.GROQ_API_KEY;
    if (!groqApiKey) {
      sails.log.warn('Groq API key not configured, skipping LLM integration');
      throw 'configError';
    }

    try {
      const groq = new Groq({
        apiKey: groqApiKey,
      });

      // Prepare card context for LLM
      const cardContext = {
        name: inputs.card.name,
        description: inputs.card.description || '',
        type: inputs.card.type,
        listName: inputs.list.name,
        listType: inputs.list.type,
        boardName: inputs.board.name,
        dueDate: inputs.card.dueDate || null,
      };

      // Create prompt for structured analysis
      const systemPrompt = `You are an AI assistant helping with project management. Analyze the provided card information and generate a structured response with the following JSON format:
{
  "priority": "high|medium|low",
  "estimatedHours": number,
  "suggestedTags": ["tag1", "tag2"],
  "riskFactors": ["factor1", "factor2"],
  "dependencies": ["dependency1", "dependency2"],
  "nextSteps": ["step1", "step2"],
  "summary": "Brief summary of the card analysis"
}

Base your analysis on the card's name, description, type, and context within the list and board.`;

      const userPrompt = `Analyze this card:
Card Name: ${cardContext.name}
Description: ${cardContext.description}
Type: ${cardContext.type}
List: ${cardContext.listName} (${cardContext.listType})
Board: ${cardContext.boardName}
Due Date: ${cardContext.dueDate || 'Not set'}

Please provide a structured analysis in the specified JSON format.`;

      const chatCompletion = await groq.chat.completions.create({
        messages: [
          {
            role: 'system',
            content: systemPrompt,
          },
          {
            role: 'user',
            content: userPrompt,
          },
        ],
        model: 'llama3-8b-8192', // Using Llama 3 8B model
        temperature: 0.3,
        max_tokens: 1024,
        top_p: 1,
      });

      const responseContent =
        chatCompletion.choices[0] &&
        chatCompletion.choices[0].message &&
        chatCompletion.choices[0].message.content;
      if (!responseContent) {
        throw new Error('No response content from Groq API');
      }

      // Try to parse the JSON response
      let structuredResponse;
      try {
        structuredResponse = JSON.parse(responseContent);
      } catch (parseError) {
        // If parsing fails, create a fallback response
        sails.log.warn('Failed to parse LLM response as JSON, using fallback', parseError);
        structuredResponse = {
          priority: 'medium',
          estimatedHours: 1,
          suggestedTags: [],
          riskFactors: [],
          dependencies: [],
          nextSteps: [],
          summary: 'Analysis generated by AI assistant',
          rawResponse: responseContent,
        };
      }

      // Add metadata
      structuredResponse.generatedAt = new Date().toISOString();
      structuredResponse.model = 'llama3-8b-8192';

      return structuredResponse;
    } catch (error) {
      sails.log.error('Error calling Groq API:', error);
      throw 'apiError';
    }
  },
};
